version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:4.0.3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "8000:5672"
      - "8001:15672"
